# Generated by Django 5.2.6 on 2025-09-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_client_options_remove_client_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['name'], 'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['platform'], 'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='order',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='order',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='order',
        ),
    ]
