# Generated by Django 5.2.6 on 2025-09-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_project_options_alter_projectcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video_url',
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, AVI, MOV, etc.)', null=True, upload_to='videos/'),
        ),
    ]
