# Generated by Django 5.2.6 on 2025-09-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_project_video_url_project_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('check', '✓ - Checkmark'), ('recycle', '♻ - Recycle'), ('handshake', '🤝 - Handshake'), ('clock', '⏱ - Clock'), ('quality', '🏆 - Trophy'), ('innovation', '💡 - Lightbulb')], default='check', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Value',
                'verbose_name_plural': 'Company Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Content Snippet',
                'verbose_name_plural': 'Content Snippets',
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to Bring Your Vision to Life?', max_length=200)),
                ('description', models.TextField(default='Join our family of satisfied clients and experience the Dimma difference')),
                ('button_text', models.CharField(default='Call Us', max_length=50)),
                ('phone_number', models.CharField(default='+251911224244', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line_1', models.CharField(default='Our Story of', max_length=100)),
                ('title_line_2', models.CharField(default='Innovation', max_length=100)),
                ('subtitle', models.TextField(default="Three decades of transforming Ethiopia's printing landscape")),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='SisterCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(help_text='Paste SVG code here')),
                ('services', models.JSONField(default=list, help_text='List of services as JSON array')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sister Company',
                'verbose_name_plural': 'Sister Companies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., 1990s, 2000s, etc.', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/timeline/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if not uploading')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order'],
            },
        ),
    ]
