# Generated by Django 5.2.6 on 2025-10-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_companyvalue_contentsnippet_ctasection_herosection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='year',
        ),
    ]
